# Permalinks
#
# Use of `relative_permalinks` ensures post links from the index work properly.
permalink:           pretty
relative_permalinks: true

# Setup
title:               SLASH2
tagline:             'distributed WAN file system'
description:         '.'
url:                 http://slash2.psc.edu/
baseurl:             'https://pscedu.github.io/slash2/'
paginate:            5

# About/contact
author:
  name:              Pittsburgh Supercomputing Center
  url:               http://www.psc.edu/
  email:             remarks@psc.edu

# Custom vars
version:             1.0.0
